// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNe2YNwBSVxP4hCyAqMxNIT7Xn1lXWqTY',
    appId: '1:421153587020:web:92670c053c9ac13c6919e9',
    messagingSenderId: '421153587020',
    projectId: 'todo-2183c',
    authDomain: 'todo-2183c.firebaseapp.com',
    storageBucket: 'todo-2183c.appspot.com',
    measurementId: 'G-RNJGX73XKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyPlzeuwy7g37JDNeiYON5df_tg1K6Hfc',
    appId: '1:421153587020:android:7c4cfa5ce4e60fcb6919e9',
    messagingSenderId: '421153587020',
    projectId: 'todo-2183c',
    storageBucket: 'todo-2183c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCnIukkS2seQORGI3ztegnTU8ltKfmkL0',
    appId: '1:421153587020:ios:305295998c4f7f086919e9',
    messagingSenderId: '421153587020',
    projectId: 'todo-2183c',
    storageBucket: 'todo-2183c.appspot.com',
    iosBundleId: 'com.example.todoListFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCnIukkS2seQORGI3ztegnTU8ltKfmkL0',
    appId: '1:421153587020:ios:305295998c4f7f086919e9',
    messagingSenderId: '421153587020',
    projectId: 'todo-2183c',
    storageBucket: 'todo-2183c.appspot.com',
    iosBundleId: 'com.example.todoListFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNe2YNwBSVxP4hCyAqMxNIT7Xn1lXWqTY',
    appId: '1:421153587020:web:4a41824ff93d7b426919e9',
    messagingSenderId: '421153587020',
    projectId: 'todo-2183c',
    authDomain: 'todo-2183c.firebaseapp.com',
    storageBucket: 'todo-2183c.appspot.com',
    measurementId: 'G-M7VZP8EXJQ',
  );
}
